# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: Daniel Jorge
author-title: Full Stack Developer
gravatar: d36a082aacb53b6f76869748fb4b81d4
email: danjorge@gmail.com
twitter: danjsouza
github: danjorge
googleplus: https://plus.google.com/u/0/104795548920256557273
facebook: danieljsouza
linkedin: www.linkedin.com/in/danjsouza
bio: "Brazilian developer. Game, music and technology lover.
      I graduated in Systems Analysis and Development at University of Fortaleza (UNIFOR). I love to study and learn new skills,
      exchange work and study experience with people around me and share my knowledge with the ones that want it. I work with Web Development since 2013 at 
      Department of Planning and the State Management and with
      Mobile Development since 2014 as Student.
      I like to work with both: Front-End and Back-End development. I work with some languages, frameworks and technologies."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values
front-end:
  - name: HTML 5
    level: 4
  - name: CSS 3
    level: 4
  - name: JavaScript
    level: 3
  - name: jQuery
    level: 3
  - name: Angular
    level: 3
  - name: Bootstrap
    level: 3
  - name: Materialize CSS
    level: 3
  - name: LESS
    level: 1
  - name: SASS
    level: 1
  - name: Gulp
    level: 3
  - name: Bower
    level: 3

back-end:
  - name: PHP
    level: 1
  - name: Node.js
    level: 3
  - name: Ruby
    level: 1
  - name: Python
    level: 1
  - name: Java
    level: 4
  - name: SQL
    level: 4

mobile:
  - name: Android
    level: 4
  - name: Ionic
    level: 1

db:
  - name: MySQL
    level: 3
  - name: PostgreSQL
    level: 3
  - name: MongoDB
    level: 1
  - name: SQL Server
    level: 2
  - name: Oracle
    level: 3
  - name: Firebase
    level: 3
  - name: NoSQL
    level: 1

devops:
  - name: Docker
    level: 1
  - name: Jenkins
    level: 1
  - name: Git
    level: 4
  - name: Apache Maven
    level: 3
  - name: Continuous Integration
    level: 3

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 4
  - name: RUP
    level: 3

others:
  - name: Web Services
    level: 5
  - name: REST
    level: 5
  - name: JEE, JSF, JPA, EJB, CDI
    level: 4
  - name: iReport, Jasper Reports
    level: 4
  - name: Hibernate
    level: 3
  - name: Ruby on Rails
    level: 1
  - name: Spring
    level: 3

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
